# Generated by Django 4.2.3 on 2023-09-04 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время рассылки')),
                ('interval', models.CharField(choices=[('Раз в день', 'Day'), ('Раз в неделю', 'Week'), ('Раз в месяц', 'Month')], default='Раз в день', max_length=15, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('Создана', 'Created'), ('Запущена', 'Running'), ('Завершена', 'Finished')], default='Создана', max_length=10, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(to='mailing.client')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_object', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема письма')),
                ('message_body', models.TextField(max_length=2000, verbose_name='Тело письма')),
                ('mailing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mailing.mailing')),
            ],
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время последней попытки')),
                ('status', models.CharField(choices=[('Успешно', 'Success'), ('Неудача', 'Failed')], max_length=7, verbose_name='Статус отправки')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
        ),
    ]
